name = "bursa-musangking-strategy-terminal"
main = "worker.js"
compatibility_date = "2024-11-01"

[assets]
directory = "../public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "bursa-musangking-strategy-terminal"
database_id = "4c9bbff9-8007-4769-90b3-e79bbce4d338"

[vars]
APP_TITLE = "Bursa Strategy Terminal"
GH_OWNER = "yankkhaing-watermelon"
GH_REPO  = "StrategyTerminal"
GH_BRANCH = "main"
PREVIEW_WORKFLOW = "preview.yml"
